### ISSUE TITLE
🐛 [BUG] - search_db failing due to extra field in API respnse

### ISSUE THREAD

**Issue by hochbergg** [ultimate-notion/ultimate-notion#27]
### Problem description

When trying to search_db, Ultimate Notion fails and shows the following messsage:

Traceback (most recent call last):
  File "/Users/galth/Documents/autocrm/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/Users/galth/Documents/autocrm/main.py", line 96, in <module>
    people = notion.search_db('People')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/galth/Documents/autocrm/.venv/lib/python3.12/site-packages/ultimate_notion/session.py", line 199, in search_db
    dbs = [cast(Database, self.cache.setdefault(db.id, Database.wrap_obj_ref(db))) for db in query.execute()]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/galth/Documents/autocrm/.venv/lib/python3.12/site-packages/ultimate_notion/obj_api/iterator.py", line 158, in __call__
    api_list = ObjectList.model_validate(result_page)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/galth/Documents/autocrm/.venv/lib/python3.12/site-packages/pydantic/main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ObjectList
results.0.in_trash
  Extra inputs are not permitted [type=extra_forbidden, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden

### Expected behaviour

Search db should return the database object

### Steps to reproduce

Run session.search_db(<db_name>)

It seems Notion is now return an 'in_trash' field

### Version

0.4

### Installation

uv pip

### Python version

3.12

### Operating system

Mac Os Sonoma

**Comment by al1p** [comment]
Hi, I added the missing `in_trash` variable [here](https://github.com/al1p/ultimate-notion/tree/NotionObject_in_trash)

Also, I had to hack a work-around when the "User" object has no type (and interrupt the recursion). 

Tests are ok, but I'm not sure about other possible side-effects, I don't think this is ready for PR...

**Comment by FlorianWilhelm** [comment]
Hi @al1p, thanks! Sorry, that I haven't had a chance to look into this. There was quit a lot going on in the last weeks. Would you provide a PR? 

In the next release, I'll also make sure that by default optional fields with Pydantic are allowed. The Notion API is still too much under development to keep them fixed.

**Comment by al1p** [comment]
Here you are : https://github.com/ultimate-notion/ultimate-notion/pull/30

**Comment by FlorianWilhelm** [comment]
Thank you @al1p.

So this is fixed on main branch and will be in the next release.

**Comment by FlorianWilhelm** [comment]
... thanks @hochbergg for reporting this issue and sorry for the long delay.
