### ISSUE TITLE
💡 [REQUEST] Query w/Filter & Pagenation

### ISSUE THREAD

**Issue by ProtossDragoon** [ultimate-notion/ultimate-notion#50]
### Describe your use-case or problem

First of all, thank you for creating this excellent project. I'm currently using Notion as a simple database for prototyping products. I believe the filter functionality that Notion provides natively could be very useful in this context.

Additionally, I couldn't find any mention of pagination in the documentation. I need a feature that automatically handles cases where there are more than 50 pages or when relations exceed 25 items.

### Proposed solution / feature

(1) Implement Notion's native filter functionality
(2) Automatic pagination handling for: a) Cases where there are more than 50 pages b) Situations where relations exceed 25 items

These features would enhance the usability of Ultimate Notion for prototyping and database management, making our lives much easier when working with not 'tiny'-sized database :)

**Comment by FlorianWilhelm** [comment]
Hi @ProtossDragoon, 

thanks for posting this issue and it's cool to hear that you like Ultimate Notion. I am currently working on integrating comments into Ultimate Notion and after that the next feature will be your point (1), i.e. the implementation of of Notion's native filter functionality. These features will be part of version 0.7.

Regarding your point (2a). Do you have problems right now when retrieving the content of databases with more than 50 pages in it? Right now I have no unit test for this, but I assumed it will work right of the box as I am using the functionality of [notion-sdk-py](https://github.com/ramnes/notion-sdk-py/) to resolve pagination. If this doesn't work for you, please file a separate bug report as a new issue.  

Regarding (2b). There is already a ToDo: in my source code about that. Currently pages are retrieved with the corresponding pages endpoint and that results in properties with a maximum of 25 items. I need to call the PageProperties endpoint on all properties with 25 items in it to potentially resolve more. This can also be regarded as a bug right now. Would you be so nice to file a separate bug report for this?

**Comment by FlorianWilhelm** [comment]
Resolved with PR #51  and PR #53.
